service: products
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: '489669634691_Siarhei_Drozd'
  region: 'us-east-1'
  stage: dev

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: /products
          method: get
          cors: true
  getProductsById:
    handler: handler.getProductsById
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true
